name: flex_color_scheme
description: A Flutter package to make and use beautiful color scheme based MaterialApp themes.
version: 1.4.1
homepage: https://github.com/rydmike/flex_color_scheme

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
